# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
#
# Translators:
msgid ""
msgstr ""
"Project-Id-Version: usb-creator\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2015-11-09 10:45+0100\n"
"PO-Revision-Date: 2015-11-05 19:51+0000\n"
"Last-Translator: pitfd <pitfd@openmailbox.org>\n"
"Language-Team: German (http://www.transifex.com/solydxk/usb-creator/language/"
"de/)\n"
"Language: de\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"

#: ../usr/lib/usb-creator/main.py:37
msgid "Unexpected error"
msgstr "Unerwarteter Fehler"

#: ../usr/lib/usb-creator/main.py:38
msgid ""
"USB Creator has failed with the following unexpected error. Please submit a "
"bug report!"
msgstr ""
"USB Creator hat den folgenden unerwarteten Fehler zurückgemeldet.\n"
"Bitte reichen Sie einen Fehlerbericht ein!"

#: ../usr/lib/usb-creator/usbcreator.py:64
#: ../usr/share/applications/usb-creator.desktop.in.h:1
msgid "USB Creator"
msgstr "USB Creator"

#: ../usr/lib/usb-creator/usbcreator.py:65
msgid "Device"
msgstr "Gerät"

#: ../usr/lib/usb-creator/usbcreator.py:66
msgid "USB"
msgstr "USB"

#: ../usr/lib/usb-creator/usbcreator.py:67
msgid "Available"
msgstr "Verfügbar:"

#: ../usr/lib/usb-creator/usbcreator.py:68
msgid "Required"
msgstr "Erforderlich"

#: ../usr/lib/usb-creator/usbcreator.py:69
msgid "Format device"
msgstr "Gerät formatieren"

#: ../usr/lib/usb-creator/usbcreator.py:70
msgid "Warning: all data will be lost"
msgstr "Warnung: alle Daten werden gelöscht"

#: ../usr/lib/usb-creator/usbcreator.py:71
msgid "Repair device"
msgstr "Gerät reparieren"

#: ../usr/lib/usb-creator/usbcreator.py:72
msgid "Tries to repair an unbootable USB"
msgstr "Es wird versucht ein nicht mehr startfähiges USB Gerät zu reparieren"

#: ../usr/lib/usb-creator/usbcreator.py:73
msgid "Execute"
msgstr "Ausführen"

#: ../usr/lib/usb-creator/usbcreator.py:74
msgid "ISO"
msgstr "ISO"

#: ../usr/lib/usb-creator/usbcreator.py:75
msgid "Delete"
msgstr "Löschen"

#: ../usr/lib/usb-creator/usbcreator.py:76
msgid "Refresh device list"
msgstr "Geräteliste aktualisieren"

#: ../usr/lib/usb-creator/usbcreator.py:77
msgid "Unmount device"
msgstr "Gerät aushängen"

#: ../usr/lib/usb-creator/usbcreator.py:78
msgid "Browse for ISO file"
msgstr "Suche nach der ISO Datei"

#: ../usr/lib/usb-creator/usbcreator.py:79
msgid "Clear the ISO field"
msgstr "ISO Feld freigeben"

#: ../usr/lib/usb-creator/usbcreator.py:83
msgid "Partitioning USB..."
msgstr "USB Gerät wird partitioniert"

#: ../usr/lib/usb-creator/usbcreator.py:84
msgid "Searching for bad block"
msgstr "Suche beschädigte Blöcke"

#: ../usr/lib/usb-creator/usbcreator.py:85
msgid "Installing Grub..."
msgstr "Grub wird installiert"

#: ../usr/lib/usb-creator/usbcreator.py:86
msgid "Start copying ISO..."
msgstr "Das Kopieren der ISO Datei wird gestartet ..."

#: ../usr/lib/usb-creator/usbcreator.py:87
msgid "kB left to copy:"
msgstr "noch KB müssen kopiert werden"

#: ../usr/lib/usb-creator/usbcreator.py:88
msgid "Check md5sum of ISO..."
msgstr "MD5Summe der ISO Datei wird überprüft..."

#: ../usr/lib/usb-creator/usbcreator.py:125
msgid "Version"
msgstr "Version"

#: ../usr/lib/usb-creator/usbcreator.py:144
msgid ""
"Cannot add ISO from path: {}.\n"
"Please, remove the ISO path or browse for an existing ISO."
msgstr ""
"ISO Datei kann nicht aus dem Pfad {} hinzugefügt werden \n"
"Bitte ändern Sie den Pfad zur oder suchen Sie eine existierende ISO Datei."

#: ../usr/lib/usb-creator/usbcreator.py:154
msgid ""
"There is not enough space available on the pen drive.\n"
"Please, remove unneeded files before continuing."
msgstr ""
"Auf dem USB Stick ist nicht genügend Platz verfügbar\n"
"Bitte entfernen Sie nicht mehr benötigte Datein, bevor Sie fortfahren."

#: ../usr/lib/usb-creator/usbcreator.py:177
msgid "Are you sure you want to remove the selected ISO from the device?"
msgstr ""
"Sind Sie sicher, dass Sie die ausgewählte ISO Datei vom Gerät entfernen "
"möchten?"

#: ../usr/lib/usb-creator/usbcreator.py:198
msgid "Select ISO"
msgstr "Wählen Sie eine ISO Datei"

#: ../usr/lib/usb-creator/usbcreator.py:251
msgid "Unmount"
msgstr "Aushängen"

#: ../usr/lib/usb-creator/usbcreator.py:256
msgid ""
"Could not unmount the device.\n"
"Please unmount the device manually."
msgstr ""
"Das Gerät konnte nicht ausgehängt werden.\n"
"Bitte hängen Sie das Gerät manuell aus."

#: ../usr/lib/usb-creator/usbcreator.py:259
msgid "You can now safely remove the device."
msgstr "Jetzt können Sie das Gerät sicher entfernen."

#: ../usr/lib/usb-creator/usbcreator.py:501
msgid "Run this application with root permission."
msgstr "Diese Programm kann nur mit Root-Rechten ausgeführt werden"

#: ../usr/lib/usb-creator/usbcreator.py:503
msgid "Wrong arguments were passed to usb-creator."
msgstr "Falsche Argumente wurden an den USB-Creator übergeben."

#: ../usr/lib/usb-creator/usbcreator.py:505
msgid "The device was not found or no device was given."
msgstr "Das Gerät wurde nicht gefunden oder es wurde kein Gerät angegeben."

#: ../usr/lib/usb-creator/usbcreator.py:507
msgid "Given ISO path was not found."
msgstr "Der angegebene Pfad zur ISO Datei wurde nicht gefunden."

#: ../usr/lib/usb-creator/usbcreator.py:509
msgid "Device is in use by another application."
msgstr "Das Gerät wird derzeit durch eine andere Anwendung benutzt."

#: ../usr/lib/usb-creator/usbcreator.py:511
msgid "Unable to mount the device."
msgstr "Das Gerät kann nicht eingehängt werden."

#: ../usr/lib/usb-creator/usbcreator.py:513
msgid "Md5sum mismatch."
msgstr "MD5Summe stimmt nicht überein"

#: ../usr/lib/usb-creator/usbcreator.py:515
msgid "The device has no fat32 partition."
msgstr "Keine FAT32 Partition vorhanden."

#: ../usr/lib/usb-creator/usbcreator.py:517
msgid "The device has no bootloader installed."
msgstr "Auf dem Gerät ist kein Bootloader installiert."

#: ../usr/lib/usb-creator/usbcreator.py:519
msgid "There is not enough space available on the device."
msgstr "Auf dem Gerät ist nicht genügend Platz vorhanden."

#: ../usr/lib/usb-creator/usbcreator.py:521
msgid ""
"An unknown error accured.\n"
"Please, visit our forum for support: http://forums.solydxk.com"
msgstr ""
"Es ist ein unbekannter Fehler aufgetreten\n"
"Bitte besuchen Sie unser Forum für weitere Unterstützung: http://forums."
"solydxk.com"

#: ../usr/lib/usb-creator/usbcreator.py:525
msgid "The USB was successfully written."
msgstr "Der USB Stick wurde erfolgreich beschrieben."

#: ../usr/share/kde4/apps/solid/actions/usb-constructor-openusb.desktop.in.h:1
msgid "Create a multi-boot USB with the USB Creator"
msgstr "Erstelle einen Multi-Boot USB Stick mit dem USB Creator"

#: ../usr/share/applications/usb-creator.desktop.in.h:2
msgid "Create a multi-boot USB"
msgstr "Erstelle einen Multi-Boot"
