# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
#
# Translators:
# Ilinsky Mikhail <mail@milinsky.com>, 2015
msgid ""
msgstr ""
"Project-Id-Version: usb-creator\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2015-11-11 23:01+0100\n"
"PO-Revision-Date: 2015-11-09 13:45+0000\n"
"Last-Translator: Ilinsky Mikhail <mail@milinsky.com>\n"
"Language-Team: Russian (http://www.transifex.com/solydxk/usb-creator/"
"language/ru/)\n"
"Language: ru\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=4; plural=(n%10==1 && n%100!=11 ? 0 : n%10>=2 && n"
"%10<=4 && (n%100<12 || n%100>14) ? 1 : n%10==0 || (n%10>=5 && n%10<=9) || (n"
"%100>=11 && n%100<=14)? 2 : 3);\n"

#: ../usr/lib/usb-creator/main.py:37
msgid "Unexpected error"
msgstr "Непредвиденная ошибка"

#: ../usr/lib/usb-creator/main.py:38
msgid ""
"USB Creator has failed with the following unexpected error. Please submit a "
"bug report!"
msgstr ""
"В приложении USB Creator произошла непредвиденная ошибка. Пожалуйста, "
"отправьте отчет об ошибке!"

#: ../usr/lib/usb-creator/usbcreator.py:64
#: ../usr/share/applications/usb-creator.desktop.in.h:1
msgid "USB Creator"
msgstr "USB Creator - Создание загрузочной флешки."

#: ../usr/lib/usb-creator/usbcreator.py:65
msgid "Device"
msgstr "Устройство"

#: ../usr/lib/usb-creator/usbcreator.py:66
msgid "USB"
msgstr "USB"

#: ../usr/lib/usb-creator/usbcreator.py:67
msgid "Available"
msgstr "Доступный"

#: ../usr/lib/usb-creator/usbcreator.py:68
msgid "Required"
msgstr "Необходимый"

#: ../usr/lib/usb-creator/usbcreator.py:69
msgid "Format device"
msgstr "Форматировать устройство"

#: ../usr/lib/usb-creator/usbcreator.py:70
msgid "Warning: all data will be lost"
msgstr "Предупреждение: все данные будут потеряны"

#: ../usr/lib/usb-creator/usbcreator.py:71
msgid "Repair device"
msgstr "Восстановить устройство"

#: ../usr/lib/usb-creator/usbcreator.py:72
msgid "Tries to repair an unbootable USB"
msgstr "Попытаться восстановить не загружаемый USB "

#: ../usr/lib/usb-creator/usbcreator.py:73
msgid "Execute"
msgstr "Выполнить"

#: ../usr/lib/usb-creator/usbcreator.py:74
msgid "ISO"
msgstr "ISO"

#: ../usr/lib/usb-creator/usbcreator.py:75
msgid "Delete"
msgstr "Удалить"

#: ../usr/lib/usb-creator/usbcreator.py:76
msgid "Refresh device list"
msgstr "Обновить список устройств"

#: ../usr/lib/usb-creator/usbcreator.py:77
msgid "Unmount device"
msgstr "Размонтировать устройство"

#: ../usr/lib/usb-creator/usbcreator.py:78
msgid "Browse for ISO file"
msgstr "Найти ISO-файл"

#: ../usr/lib/usb-creator/usbcreator.py:79
msgid "Clear the ISO field"
msgstr "Очистить ISO поле"

#: ../usr/lib/usb-creator/usbcreator.py:83
msgid "Partitioning USB..."
msgstr "Разметка USB..."

#: ../usr/lib/usb-creator/usbcreator.py:84
msgid "Searching for bad block"
msgstr "Поиск плохих блоков"

#: ../usr/lib/usb-creator/usbcreator.py:85
msgid "Installing Grub..."
msgstr "Установка загрузчика Grub..."

#: ../usr/lib/usb-creator/usbcreator.py:86
msgid "Start copying ISO..."
msgstr "Копирование образа..."

#: ../usr/lib/usb-creator/usbcreator.py:87
msgid "kB left to copy:"
msgstr "Осталось скопировать кБ:"

#: ../usr/lib/usb-creator/usbcreator.py:88
msgid "Check md5sum of ISO..."
msgstr "Проверка md5 суммы образа..."

#: ../usr/lib/usb-creator/usbcreator.py:123
msgid "Version"
msgstr "Версия"

#: ../usr/lib/usb-creator/usbcreator.py:142
msgid ""
"Cannot add ISO from path: {}.\n"
"Please, remove the ISO path or browse for an existing ISO."
msgstr ""
"Не удается добавить образ:{}.\n"
"Пожалуйста проверьте путь или укажите другой образ."

#: ../usr/lib/usb-creator/usbcreator.py:152
msgid ""
"There is not enough space available on the pen drive.\n"
"Please, remove unneeded files before continuing."
msgstr ""
"Недостаточно места на флэш-накопителе.\n"
"Освободите место на накопителе перед продолжением."

#: ../usr/lib/usb-creator/usbcreator.py:175
msgid "Are you sure you want to remove the selected ISO from the device?"
msgstr "Вы уверены, что хотите удалить выбранный образ?"

#: ../usr/lib/usb-creator/usbcreator.py:197
msgid "Select ISO"
msgstr "Выбрать ISO-образ"

#: ../usr/lib/usb-creator/usbcreator.py:250
msgid "Unmount"
msgstr "Размонтировать"

#: ../usr/lib/usb-creator/usbcreator.py:255
msgid ""
"Could not unmount the device.\n"
"Please unmount the device manually."
msgstr ""
"Не удалось размонтировать устройство.\n"
"Пожалуйста, отключите устройство вручную."

#: ../usr/lib/usb-creator/usbcreator.py:258
msgid "You can now safely remove the device."
msgstr "Теперь вы можете безопасно извлечь устройство."

#: ../usr/lib/usb-creator/usbcreator.py:506
msgid "Run this application with root permission."
msgstr "Запустите это приложение с правами \"суперпользователя\""

#: ../usr/lib/usb-creator/usbcreator.py:508
msgid "Wrong arguments were passed to usb-creator."
msgstr "Неправильные аргументы были приняты к usb-creator."

#: ../usr/lib/usb-creator/usbcreator.py:510
msgid "The device was not found or no device was given."
msgstr "Устройство не найдено."

#: ../usr/lib/usb-creator/usbcreator.py:512
msgid "Given ISO path was not found."
msgstr "Указанный путь не  был найден."

#: ../usr/lib/usb-creator/usbcreator.py:514
msgid "Device is in use by another application."
msgstr "Устройство используется другим приложением."

#: ../usr/lib/usb-creator/usbcreator.py:516
msgid "Unable to mount the device."
msgstr "Не удается подключить устройство."

#: ../usr/lib/usb-creator/usbcreator.py:518
msgid "Md5sum mismatch."
msgstr "Md5-сумма не совпадает."

#: ../usr/lib/usb-creator/usbcreator.py:520
msgid "The device has no fat32 partition."
msgstr "Устройство не имеет разделов fat32."

#: ../usr/lib/usb-creator/usbcreator.py:522
msgid "The device has no bootloader installed."
msgstr "На устройстве не установлен загрузчик."

#: ../usr/lib/usb-creator/usbcreator.py:524
msgid "There is not enough space available on the device."
msgstr "Недостаточно места на устройстве."

#: ../usr/lib/usb-creator/usbcreator.py:526
msgid ""
"Unable to guess distribution from ISO name.\n"
"Make sure you have the distribution name in the ISO name."
msgstr ""

#: ../usr/lib/usb-creator/usbcreator.py:529
msgid ""
"An unknown error accured.\n"
"Please, visit our forum for support: http://forums.solydxk.com"
msgstr ""
"Неизвестная ошибка.\n"
"Пожалуйста, посетите наш форум http://forums.solydxk.com"

#: ../usr/lib/usb-creator/usbcreator.py:533
msgid "The USB was successfully written."
msgstr "USB был успешно записан."

#: ../usr/share/kde4/apps/solid/actions/usb-constructor-openusb.desktop.in.h:1
msgid "Create a multi-boot USB with the USB Creator"
msgstr "Создать мульти-загрузочный USB-накопитель"

#: ../usr/share/applications/usb-creator.desktop.in.h:2
msgid "Create a multi-boot USB"
msgstr "Создать мульти-загрузочный USB-накопитель"
